import {Box,Drawer,List,ListItemButton,ListItemIcon,ListItemText,Typography,Divider,Chip} from '@mui/material';
import DashboardRoundedIcon from '@mui/icons-material/DashboardRounded';
import InsightsRoundedIcon from '@mui/icons-material/InsightsRounded';
import AccountTreeRoundedIcon from '@mui/icons-material/AccountTreeRounded';
import FactCheckRoundedIcon from '@mui/icons-material/FactCheckRounded';
import PlaylistAddCheckRoundedIcon from '@mui/icons-material/PlaylistAddCheckRounded';
import HealthAndSafetyRoundedIcon from '@mui/icons-material/HealthAndSafetyRounded';
import MenuBookRoundedIcon from '@mui/icons-material/MenuBookRounded';
const items=[['Overview',DashboardRoundedIcon],['Performance Intelligence',InsightsRoundedIcon],['Operational Intelligence',AccountTreeRoundedIcon],['Findings & Decisions',FactCheckRoundedIcon],['Action Management',PlaylistAddCheckRoundedIcon],['Measurement & Data Quality',HealthAndSafetyRoundedIcon],['Methodology',MenuBookRoundedIcon]];
export default function Sidebar({mobileOpen,onClose,selected,onSelect}){const content=<Box sx={{width:{xs:280,sm:292},height:'100%',display:'flex',flexDirection:'column'}}><Box sx={{p:2.5}}><Typography variant="overline" sx={{letterSpacing:1.7,color:'primary.main',fontWeight:800}}>MPCA FLOOD RESPONSE</Typography><Typography variant="h6" sx={{fontWeight:800,lineHeight:1.15,mt:.5}}>MEAL Decision<br/>Intelligence Platform</Typography><Chip size="small" label="SOURCE-LOCKED" sx={{mt:1.5,bgcolor:'rgba(103,232,249,.08)',color:'primary.main',border:'1px solid rgba(103,232,249,.18)'}}/></Box><Divider/><List sx={{px:1.25,py:1.5}}>{items.map(([label,Icon])=><ListItemButton aria-current={selected===label ? 'page' : undefined} key={label} selected={selected===label} onClick={()=>{onSelect(label);onClose?.()}} sx={{mb:.5,borderRadius:2.5,py:1.05,'&.Mui-selected':{bgcolor:'rgba(103,232,249,.09)',color:'primary.main'},'&.Mui-selected .MuiListItemIcon-root':{color:'primary.main'}}}><ListItemIcon sx={{minWidth:38,color:'text.secondary'}}><Icon fontSize="small"/></ListItemIcon><ListItemText primary={label} primaryTypographyProps={{fontSize:13.5,fontWeight:selected===label?750:550}}/></ListItemButton>)}</List><Box sx={{mt:'auto',p:2}}><Box sx={{p:1.5,borderRadius:3,bgcolor:'rgba(167,139,250,.06)',border:'1px solid rgba(167,139,250,.14)'}}><Typography variant="caption" color="text.secondary">Analytical principle</Typography><Typography variant="body2" sx={{mt:.5,fontWeight:650}}>Build the interface around the evidence. Do not generate additional evidence.</Typography></Box></Box></Box>;return <><Drawer aria-label="Primary navigation" variant="permanent" sx={{display:{xs:'none',md:'block'},'& .MuiDrawer-paper':{width:292}}} open>{content}</Drawer><Drawer aria-label="Mobile navigation" variant="temporary" open={mobileOpen} onClose={onClose} sx={{display:{xs:'block',md:'none'}}}>{content}</Drawer></>}
